### ISSUE TITLE
Drake's crawler warning dialog disappears

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#187]
**Describe the bug**
Drake's dialog choice about the Minecrawler warning disappears after loading a savegame, if the player didn't have a beer.

**Expected behavior**
Drake's dialog choice about the Minecrawler warning no longer disappears, if the player didn't have a beer.

**Steps to reproduce the issue**
1. Offer Drake a beer without having one in the inventory.
2. Save the game.
3. Load the save.
4. The dialog choice disappeared.

**Additional context**
https://github.com/AmProsius/gothic-1-community-patch/blob/839bd35f840802afb4884d69a79a7df3bfa050f9/scriptbase/_work/Data/Scripts/Content/Story/Missions/DIA_GRD_260_Drake.d#L55-L97

**Comment by AmProsius** [comment]
Part of the solution might be to change
https://github.com/AmProsius/gothic-1-community-patch/blob/839bd35f840802afb4884d69a79a7df3bfa050f9/scriptbase/_work/Data/Scripts/Content/Story/Missions/DIA_GRD_260_Drake.d#L61

to

```d
    permanent       = 1;
```

but then the condition has to be updated as well. Unfortunately I don't know yet how to check if the dialog was already spoken..

**Comment by szapp** [comment]
There is no way to check if the beer was given if the patch is installed after the dialog was spoken. On the other hand, if we unlock that dialog again, it will be completely out of context later. Imagine having beaten the mine crawlers and leaving the mine, Drake stops the player to announce he should join the guards. The dialog option "(give beer)" and the corresponding dialog then make no sense at all. It's part of the conversion connected to `Grd_260_Drake_Gefahr`.

To me any sort of fix will be only half-working and not satisfactory as well.

I think the dialog could just be left as it is right now: If the player didn't have a beer but claimed he had one: Tough luck. There are other occasions in the game where there is only one chance to get advice, see #166 for example.

One thing could be to change the dialog condition this way:
```D
FUNC INT  Grd_260_Drake_Crawler_Okay_Condition() 
{ 
    if (Npc_KnowsInfo (hero,Grd_260_Drake_Gefahr))
    && (Npc_HasItems (hero, ItFobeer))
    { 
            return 1; 
    }; 
}; 
```
This would at least not show the dialog option if the player does not have a beer. But again this is only a half working solution, because it will only work if the dialog had not been spoken before installing the patch. And it will cause the out-of-context dialog if the player has a beer later on in the game.

I suggest to ignore this issue all together.
