### ISSUE TITLE
Torch near Old Mine can't be used

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#229]
**Describe the bug**
The torch on the watch tower near the Old Mine's entrance can't be used due to a typo.

**Expected behavior**
The torch on the watch tower near the Old Mine's entrance can now be used correctly.

**Additional context**
Bug and fix provided by [N1kX94](https://github.com/AmProsius/gothic-1-community-patch/issues/211#issuecomment-809381533).

Nearest waypoint: `OW_OM_ENTRANCE01`

VOB properties:

```		
[% oCMobFire:oCMobInter:oCMOB:zCVob 18433 14226]
pack=int:0
presetName=string:
bbox3DWS=rawFloat:-6254.104 1136.61316 -13623.71 -6187.89404 1356.81091 -13561.7793 
trafoOSToWSRot=raw:3d5ae1bebc4b3fbdfe8e653f7cdc0ebd30b07f3fc6f20e3d3db265bf496082bc7be9e1be
trafoOSToWSPos=vec3:-6216.09521 1138.06165 -13591.1494
vobName=string:OW_FIREPLACE_HIGH2_01
visual=string:FIREPLACE_HIGH2.ASC
showVisual=bool:1
visualCamAlign=enum:0
cdStatic=bool:0
cdDyn=bool:1
staticVob=bool:1
dynShadow=enum:0
[visual zCModel 0 14227]
[]
[ai % 0 0]
[]
focusName=string:TORCH
hitpoints=int:10
damage=int:0
moveable=bool:0
takeable=bool:0
focusOverride=bool:0
soundMaterial=enum:0
visualDestroyed=string:
owner=string:
ownerGuild=string:
isDestroyed=bool:0
stateNum=int:1
triggerTarget=string:
useWithItem=string:ITLSTORCGBURNING
conditionFunc=string:
onStateFunc=string:
rewind=bool:0
fireSlot=string:BIP01 FIRE
fireVobtreeName=string:FIRETREE_MEDIUM.ZEN
[]
```

**Comment by AmProsius** [comment]
```
useWithItem=string:ITLSTORCGBURNING
```

changed to

```
useWithItem=string:ITLSTORCHGBURNING
```

**Comment by szapp** [comment]
I suggest to
1. find the torch by its position `-6216.09521, 1138.06165, -13591.1494` using `G1CP_FindVobByPosF`
2. confirm that the found VOB is a `oCMobFire` object by using `Hlp_Is_oCMobFire`
3. assign it to a `oCMobInter` variable (it's not neccesary to assign it to an oCMobFire, because we are only interested in the `useWithItem`) with `var oCMobInter mob; mob = _^(vobPtr);`
4. confirm that `mob.useWithItem` is "ITLSTORCGBURNING" using `Hlp_StrCmp`

After these checks it should be expected that the correct MOB is found and that the issue was not already fixed. The property can then be adjusted.

On reverting essentially the same thing should be done. A prior check if the G1CP fix was applied (see similar revertible fixes) should be done to ensure not to revert the issue if it was not fixed by someone else.

**Comment by AmProsius** [comment]
All of the torches near the Old Mine can be lit without a problem.

![ScreenShot_2021_7_31_16_48_50](https://user-images.githubusercontent.com/2817152/127743732-ddf5dca9-e494-4198-9c0e-2dee072c1992.jpg)

**Comment by szapp** [comment]
Maybe we could write a one-use script to iterate over all torches (`oCMobFire`) in the world to check if their `useWithItem` is correctly set to `ITLSTORCHGBURNING`. That may reveal some torches that are not working.
