### ISSUE TITLE
Dungeon Key description faulty

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#49]
"des Alten Lagers" from Dungeon Key should be translated to English.

**Comment by szapp** [comment]
It seems like this issue is already fixed in the scripts we have (see below). Does it exist in the English retail version of the game?

If there are versions of the game that contain this incorrect description, we can verify it and if necessary correct it. I can't hurt - but we could save some time if it turns out, it's not necessary to fix.


https://github.com/AmProsius/gothic-1-community-patch/blob/18734a9882ea7ff5f09b7ab97c0be6ef6791f05f/scriptbase/_work/Data/Scripts/Content/Items/MissionItems_5.d#L399-L417

**Comment by szapp** [comment]
This very fix is actually mentioned [in the release of the scripts we are using](https://forum.worldofplayers.de/forum/threads/1488168-Gothic-1-08j-English-Scripts-%28review%29?p=25361398&viewfull=1#post25361398). I don't quite understand, if that was just a bug in the mod-kit scripts and the complied scripts were already correct.

**Comment by AmProsius** [comment]
I extracted the gothic.dat file of the English version from GOG and the issue seems fixed there:

```
instance dungeonkey(c_item) {
    name = "Dungeon Key";
    mainflag = item_kat_none;
    flags = item_mission;
    value = 3;
    visual = "ItKe_Key_03.3ds";
    material = mat_metal;
    description = name;
    text = "Opens the dungeons";
    text = "of the old camp.";
};
```

I will close this issue then as the issue is not present in the current retail version of the game.

**Comment by AmProsius** [comment]
This is the actual fix:
https://github.com/AmProsius/gothic-1-community-patch/blob/18734a9882ea7ff5f09b7ab97c0be6ef6791f05f/scriptbase/_work/Data/Scripts/Content/Items/MissionItems_5.d#L414-L416

changed to

```d
     description         = name; 
     TEXT[0]             = "Opens the dungeons"; 
     TEXT[1]             = "of the old camp."; 
```

**Comment by szapp** [comment]
Could someone confirm if this is still a language dependent bug, or the scripts look the same in the German localization?

**Comment by AmProsius** [comment]
The bug is also present in the German scripts:

```d
	description			= name;
	TEXT[0]				= "öffnet den Kerker";
	TEXT[0]				= "des Alten Lagers.";
```

**Comment by AmProsius** [comment]
I guess this fix can be simplified by using the `G1CP_SetStringConst()` function, right?
