### ISSUE TITLE
Humans don't recognise orcs as monsters

### ISSUE THREAD

**Issue by i5sue5** [AmProsius/gothic-1-community-patch#78]
Humans ignore orcs until they're attacked by them. It's an old oversight from the alpha stage of the game where more interaction with orcs was planned.

**Comment by i5sue5** [comment]
---------------------------------
_work/data/Scripts/content/AI/AI_Intern/C_Functions.d:
-----------------------------------

```
func int C_NpcIsMonster(var C_NPC slf)
{
	PrintDebugNpc		(PD_ZS_DETAIL,"C_NpcIsMonster");
	PrintDebugString	(PD_ZS_DETAIL,"...name: ", slf.name);

	if (slf.guild > GIL_SEPERATOR_HUM)
	{
		PrintDebugNpc	(PD_ZS_DETAIL,"...true");
		return TRUE;
	}
	else
	{
		PrintDebugNpc	(PD_ZS_DETAIL,"...false");
		return FALSE;
	};
};
```

This will fix the issue.

**Comment by szapp** [comment]
I am a bit hesitant about this fix, because there is a dedicated, analogous function for orcs (see below) and in the engine the guilds of orcs are also hard coded and often treated separately from monsters (after all they have humanoid models with dedicated head visuals and more elaborate ZS states, which makes them actually more similar to humans).
https://github.com/AmProsius/gothic-1-community-patch/blob/18734a9882ea7ff5f09b7ab97c0be6ef6791f05f/scriptbase/_work/Data/Scripts/Content/AI/AI_Intern/C_Functions.d#L184-L191

___

Also, from the calls to this function is becomes apparent that orcs are treated differently from monsters. (Changing that function would have break some ZS states of orcs.) Some examples:
https://github.com/AmProsius/gothic-1-community-patch/blob/18734a9882ea7ff5f09b7ab97c0be6ef6791f05f/scriptbase/_work/Data/Scripts/Content/AI/ZS_Human/ZS_ReactToDamage.d#L51-L54
https://github.com/AmProsius/gothic-1-community-patch/blob/18734a9882ea7ff5f09b7ab97c0be6ef6791f05f/scriptbase/_work/Data/Scripts/Content/Magic/ZS/ZS_MagicFreeze.d#L8-L16

I think it would be dangerous to change that function. Instead, it seems like a guild-attitudes issue to me - although the monster attitudes look fine too:
https://github.com/AmProsius/gothic-1-community-patch/blob/18734a9882ea7ff5f09b7ab97c0be6ef6791f05f/scriptbase/_work/Data/Scripts/Content/AI/B_Monster/B_InitMonsterAttitudes.d#L484-L487

I would rather investigate a bit further as to where exactly lies the origin for them not attacking.

___

In the end it comes down to this important question:

#### Is it noticeable? Do humans ever even encounter orcs in the vanilla game?

Because if it's not, I would stay away from it, to not mess up any mods that may depend on this behavior.

**Comment by szapp** [comment]
I think the function to modify is `C_NpcIsDangerousMonster`. It seems exclusively used to determine actions in fighting context.
https://github.com/AmProsius/gothic-1-community-patch/blob/e57233a2f781034e87b532670f1995177753f75c/scriptbase/_work/Data/Scripts/Content/AI/AI_Intern/C_Functions.d#L168-L183




Here are the three contexts in which this function is called. The second one explicitly states that orcs are included. So I suppose to modify the function above and add `C_NpcIsOrc` next to `C_NpcIsMonster`.
https://github.com/AmProsius/gothic-1-community-patch/blob/e57233a2f781034e87b532670f1995177753f75c/scriptbase/_work/Data/Scripts/Content/AI/B_Human/B_AssessEnemy.d#L85-L97

https://github.com/AmProsius/gothic-1-community-patch/blob/e57233a2f781034e87b532670f1995177753f75c/scriptbase/_work/Data/Scripts/Content/AI/B_Human/B_AssessFighter.d#L155-L171

https://github.com/AmProsius/gothic-1-community-patch/blob/e57233a2f781034e87b532670f1995177753f75c/scriptbase/_work/Data/Scripts/Content/AI/B_Human/B_ObserveIntruder.d#L67-L77

**Comment by AmProsius** [comment]
> So I suppose to modify the function above and add `C_NpcIsOrc` next to `C_NpcIsMonster`.

I agree, but I'd like @i5sue5's opinion on that. He knows more about the alpha and the intentions of the developers I suppose.
