### ISSUE TITLE
NPCs freeze when fleeing 

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#9]
NPCs stand still sometimes when fleeing.

**Comment by catalinstoian** [comment]
ZS_Flee.d

	//-------- Die eigentliche Flucht -------- 
	else
	{
		PrintDebugNpc	(PD_ZS_CHECK,	"...Gegner noch zu nah dran!");			
		Npc_SetTarget	(self,	other);	
		
		Npc_GetTarget	( self);
		AI_Flee			(self);										// ...also weiter fliehen!
//		AI_Wait			(self,	1);
		return			LOOP_CONTINUE;
	};

**Comment by szapp** [comment]
The wait command was actually *not* the cause of the NPC freezing. I noticed that the previously implemented fix of removing that wait instruction did not solve the freezing.

The freeze is actually due to the NPC being partially out of slight of the origin NPC. That causes the flee-routing (inside `AI_Flee`) to be interrupted.

In a refactoring, the NPC now turns to the origin NPC in these cases which looks more natural. As soon as line of sight is re-established the NPC continues to flee. This looks like the NPC is checking if the origin NPC will chase them or if it's safe to resume the daily routine.

This is strictly not a fix but a very safe and minimally invasive improvement.

@AmProsius As part of the big refactoring effort in #460, there is no separate pull request for this change. I hope that's okay.

**Comment by szapp** [comment]
An alternative would be a more direct approach where the check for line of sight in `AI_Flee` is relaxed to "is NPC visible on screen (or in line of sight of origin NPC)".

This would be an actual fix but might have unforeseeable side effects.

**Comment by AmProsius** [comment]
Let's go with the minimally invasive fix first and keep it if there is no more feedback on the issue.
